services:
  database:
    image: postgres:alpine
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=z-prefix
    ports:
      - '5432:5432'
    restart: always

  api:
    build: api
    volumes:
      - ./api:/server
    ports:
      - 3001:3001
    depends_on:
      - "database"

volumes:
  z-prefix: {}